config/routes.rb
Teste4::Application.routes.draw do

	match 'm' => 'mobile#index', :as => 'mobile_home'
	match 'm/info' => 'mobile#info', :as => 'mobile_info'
	match 'm/:assunto_id/areas' => 'mobile#lista_area', :as => 'areas_mobile'
	match 'm/:area_id/categorias' => 'mobile#lista_categoria', :as => 'categorias_mobile'
	match 'm/:categoria_id/perfis' => 'mobile#lista_perfil', :as => 'perfis_mobile'
	match 'm/:parm/posts' => 'mobile#twitter', :as => 'twitter_mobile'
	#match 'm/:perfil_id/posts' => 'mobile#twitter', :as => 'twitter_mobile'

	resources :perfis

	resources :categorias

	resources :areas

	resources :assuntos
	
	devise_for :admins,
			:path => '/',
			:path_names => {
				:sign_in  => 'entrar',
				:sign_out => 'sair',
				:sign_up => 'registrar'}

	root :to => "home#index"


	# See how all your routes lay out with "rake routes"
end

app/controllers/mobile_controller.rb
# coding: utf-8
class MobileController < ApplicationController
	def index
		@assunto = Assunto.first
		@titulo = @assunto.nome
	end

	def info
		@titulo = 'Informações'
		@assunto = Assunto.first
	end
	
	def lista_area
		@areas = Area.find_all_by_assunto_id params[:assunto_id]
		@titulo = 'Áreas'
	end

	def lista_categoria
		@categorias = Categoria.find_all_by_area_id params[:area_id]
		@area = Area.find_by_id params[:area_id]
		@titulo = @area.nome
	end

	def lista_perfil
		@perfis = Perfil.find_all_by_categoria_id params[:categoria_id]
		@categoria = Categoria.find_by_id params[:categoria_id]
		@titulo = @categoria.nome
	end

	def twitter
		if params[:parm].to_i.to_s != "0"
			@perfil = Perfil.find_by_id params[:parm]	#params[:perfil_id]
			@screen_name = @perfil.user
		else
			@screen_name = params[:parm]
		end
		
		@go_twitter = "http://twitter.com/" + @screen_name
		
		@resultados = Twitter.user_timeline(@screen_name, {:count => 20})
			  
		if not @resultados
			@resultados = Array.new
		end

		if @resultados and not @resultados.empty?
			@imagem_perfil = @resultados[0].user.profile_image_url
			@bio = " " + @resultados[0].user.description
		else
			@imagem_perfil = Twitter.user(@screen_name).profile_image_url
			@bio = " " + Twitter.user(@screen_name).description
		end
	end

end

app/helpers/mobile_helper.rb
module MobileHelper
end

app/views/mobile/index.mobile.erb
# coding: utf-8
<div data-role="header" data-theme="b"> 
	<h1><%= @assunto.nome %></h1> 
</div><!-- /header -->

<div data-role="content">
	<%= link_to "Áreas", areas_mobile_path(@assunto.id), "data-role" => "button", "data-theme" => "d"%>
	<%= link_to "Informações", mobile_info_path, "data-role" => "button", "data-rel" => "dialog", "data-transition" => "pop", "data-theme" => "d"%>
	<%= link_to "@"+ @assunto.user, twitter_mobile_path(@assunto.user), "data-role" => "button", "data-theme" => "d"%>
</div><!-- /content -->

app/views/mobile/info.mobile.erb
# coding: utf-8
<div data-role="header" data-theme="b" data-rel="back"> 
	<h1>Informações</h1> 
</div><!-- /header -->

<div data-role="content" data-theme="b">
	
	<ul data-role="listview" data-theme="d" data-inset="true">
		<li><%= @assunto.nome %></li>
		<li><%= @assunto.info %></li>
	</ul>
</div><!-- /content -->

<div data-role="footer" data-theme="b">
</div><!-- /content -->

app/views/mobile/lista_area.mobile.erb
# coding: utf-8
<div data-role="header" data-theme="b" data-position="inline">
	<%= link_to "Voltar", "#", "data-rel" => "back", "data-direction" => "reverse", "data-icon" => "arrow-l" %>
	<h1>Áreas</h1>
	<%= link_to "Home", mobile_home_url, "data-rel" => "home", "data-direction" => "reverse", "data-icon" => "home", "data-iconpos" => "notext"%>
</div><!-- /header -->

<div data-role="content" data-theme="b">
	<ul data-role="listview" data-theme="d">
		<% @areas.each do |area| %>
			<li>
				<%= link_to area.nome, categorias_mobile_path(area.id) %>
			</li>
		<% end %>
	</ul>

</div><!-- /content -->

app/views/mobile/lista_categoria.mobile.erb
# coding: utf-8
<div data-role="header" data-theme="b">
	<%= link_to "Voltar", "#", "data-rel" => "back", "data-direction" => "reverse", "data-icon" => "arrow-l" %>
	<h1><%= @area.nome%></h1>
	<%= link_to "Home", mobile_home_url, "data-rel" => "home", "data-direction" => "reverse", "data-icon" => "home", "data-iconpos" => "notext" %>
</div><!-- /header -->

<div data-role="content" data-theme="b">
	<ul data-role="listview" data-theme="d">
		<% @categorias.each do |categ| %>
			<li>
				<%= link_to categ.nome, perfis_mobile_path(categ.id) %>
			</li>
		<% end %>
	</ul>

</div><!-- /content -->

app/views/mobile/lista_perfil.mobile.erb
# coding: utf-8
<div data-role="header" data-theme="b">
	<%= link_to "Voltar", "#", "data-rel" => "back", "data-direction" => "reverse", "data-icon" => "arrow-l" %>
	<h1><%= @categoria.nome%></h1>
	<%= link_to "Home", mobile_home_url, "data-rel" => "home", "data-direction" => "reverse", "data-icon" => "home", "data-iconpos" => "notext" %>
</div><!-- /header -->

<div data-role="content" data-theme="b">
	<ul data-role="listview" data-theme="d">
		<% @perfis.each do |perfil| %>
			<li>
				<%= link_to perfil.nome, twitter_mobile_path(perfil.id) %>
			</li>
		<% end %>
	</ul>

</div><!-- /content -->

app/views/mobile/twitter.mobile.erb
# coding: utf-8
<div data-role="header" data-theme="b" data-position="inline">
	<%= link_to "Voltar", "#", "data-rel" => "back", "data-direction" => "reverse", "data-icon" => "arrow-l" %>
	<h1>
		@<%= @screen_name %>
	</h1>
	<%= link_to "Home", mobile_home_url, "data-rel" => "home", "data-direction" => "reverse", "data-icon" => "home", "data-iconpos" => "notext" %>
	<!--<%= link_to "Atualizar", "#", "data-icon" => "refresh", "class" => "ui-btn-right" %>-->
</div>

<div data-role="content" data-theme="b">
	<div>
		<ul data-role="listview" data-theme="d" data-inset="true">
			<li>
				<img alt="<%= @screen_name %>" src="<%= @imagem_perfil %>">
				@<%= @screen_name %><br/><br/>
				<div><%= @bio %></div>
			</li>
		</ul>
	</div>

	<ul data-role="listview" data-theme="d" data-inset="true">
		<% @resultados.each_with_index do |resultado, index| %>
			<li>
				
				<%= resultado.text%>
				
			</li>	
		<% end %>
	</ul>
	
	<%= link_to "Continuar no Twitter", @go_twitter, "data-role" => "button", "data-theme" => "d", "target" => "_blank" %>
</div><!-- /content -->