config/routes.rb
Teste4::Application.routes.draw do

	match 'm' => 'mobile#index', :as => 'mobile_home'
	match 'm/info' => 'mobile#info', :as => 'mobile_info'
	match 'm/:assunto_id/areas' => 'mobile#lista_area', :as => 'areas_mobile'
	match 'm/:area_id/categorias' => 'mobile#lista_categoria', :as => 'categorias_mobile'
	match 'm/:categoria_id/perfis' => 'mobile#lista_perfil', :as => 'perfis_mobile'
	match 'm/:parm/posts' => 'mobile#twitter', :as => 'twitter_mobile'
	#match 'm/:perfil_id/posts' => 'mobile#twitter', :as => 'twitter_mobile'

	resources :perfis

	resources :categorias

	resources :areas

	resources :assuntos
	
	devise_for :admins,
			:path => '/',
			:path_names => {
				:sign_in  => 'entrar',
				:sign_out => 'sair',
				:sign_up => 'registrar'}

	root :to => "home#index"


	# See how all your routes lay out with "rake routes"
end

app/controllers/perfis_controller.rb
# coding: utf-8
class PerfisController < ApplicationController

	before_filter :authenticate_admin!

  # GET /perfis
  # GET /perfis.xml
  def index
    @perfis = Perfil.order('categoria_id ASC').all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @perfis }
    end
  end

  # GET /perfis/1
  # GET /perfis/1.xml
  def show
    @perfil = Perfil.find(params[:id])
	@cat = Categoria.find_by_id(@perfil.categoria_id)

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @perfil }
    end
  end

  # GET /perfis/new
  # GET /perfis/new.xml
  def new
    @perfil = Perfil.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @perfil }
    end
  end

  # GET /perfis/1/edit
  def edit
    @perfil = Perfil.find(params[:id])
  end

  # POST /perfis
  # POST /perfis.xml
  def create
    @perfil = Perfil.new(params[:perfil])

    respond_to do |format|
      if @perfil.save
        format.html { redirect_to(perfis_url, :notice => 'Perfil was successfully created.') }
        format.xml  { render :xml => @perfil, :status => :created, :location => @perfil }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @perfil.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /perfis/1
  # PUT /perfis/1.xml
  def update
    @perfil = Perfil.find(params[:id])

    respond_to do |format|
      if @perfil.update_attributes(params[:perfil])
        format.html { redirect_to(perfis_url, :notice => 'Perfil was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @perfil.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /perfis/1
  # DELETE /perfis/1.xml
  def destroy
    @perfil = Perfil.find(params[:id])
    @perfil.destroy

    respond_to do |format|
      format.html { redirect_to(perfis_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/perfis_helper.rb
module PerfisHelper
end

app/views/perfis/_form.html.erb
# coding: utf-8
<%= form_for(@perfil) do |f| %>
  <% if @perfil.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@perfil.errors.count, "error") %> prohibited this perfil from being saved:</h2>

      <ul>
      <% @perfil.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :categoria_id %><br />
    <!-- <%= f.text_field :categoria_id %> -->
	<%= f.collection_select(:categoria_id,
		Categoria.all,
		:id, :nome) %>	
  </div>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/perfis/edit.html.erb
# coding: utf-8
<h1>Alterar perfil</h1>

<%= render 'form' %>

<%= link_to 'Visualizar', @perfil %> |
<%= link_to 'Voltar', perfis_path %>

app/views/perfis/index.html.erb
# coding: utf-8
<h1>Manutenção de perfis</h1>

<table>
  <tr>
    <th>Categoria</th>
    <th>User</th>
    <th>Nome</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @perfis.each do |perfil| %>
  <tr>
	<% @categ = Categoria.find_by_id(perfil.categoria_id) %>
    <!-- <td><%= perfil.categoria_id %></td> -->
	<td><%= @categ.nome %></td>
    <td><%= perfil.user %></td>
    <td><%= perfil.nome %></td>
    <td><%= link_to 'Visualizar', perfil %></td>
    <td><%= link_to 'Alterar', edit_perfil_path(perfil) %></td>
    <td><%= link_to 'Excluir', perfil, :confirm => 'Confirmar exclusão?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Incluir Perfil', new_perfil_path %>

app/views/perfis/new.html.erb
# coding: utf-8
<h1>Incluir perfil</h1>

<%= render 'form' %>

<%= link_to 'Voltar', perfis_path %>

app/views/perfis/show.html.erb
# coding: utf-8
<p id="notice"><%= notice %></p>

<p>
  <b>Categoria:</b>
  <!-- <%= @perfil.categoria_id %> -->
  <%= @cat.nome %>
</p>

<p>
  <b>User:</b>
  <%= @perfil.user %>
</p>

<p>
  <b>Nome:</b>
  <%= @perfil.nome %>
</p>


<%= link_to 'Alterar', edit_perfil_path(@perfil) %> |
<%= link_to 'Voltar', perfis_path %>