config/routes.rb
Teste4::Application.routes.draw do

	match 'm' => 'mobile#index', :as => 'mobile_home'
	match 'm/info' => 'mobile#info', :as => 'mobile_info'
	match 'm/:assunto_id/areas' => 'mobile#lista_area', :as => 'areas_mobile'
	match 'm/:area_id/categorias' => 'mobile#lista_categoria', :as => 'categorias_mobile'
	match 'm/:categoria_id/perfis' => 'mobile#lista_perfil', :as => 'perfis_mobile'
	match 'm/:parm/posts' => 'mobile#twitter', :as => 'twitter_mobile'
	#match 'm/:perfil_id/posts' => 'mobile#twitter', :as => 'twitter_mobile'

	resources :perfis

	resources :categorias

	resources :areas

	resources :assuntos
	
	devise_for :admins,
			:path => '/',
			:path_names => {
				:sign_in  => 'entrar',
				:sign_out => 'sair',
				:sign_up => 'registrar'}

	root :to => "home#index"


	# See how all your routes lay out with "rake routes"
end

app/models/assunto.rb
class Assunto < ActiveRecord::Base
	has_many :areas, :dependent => :destroy
	
	validates_presence_of :nome, :message => ' deve ser preenchido.'
	validates_presence_of :user, :message => ' deve ser preenchido.'
	validates_presence_of :info, :message => ' deve ser preenchido.'
end

app/controllers/assuntos_controller.rb
# coding: utf-8
class AssuntosController < ApplicationController

	before_filter :authenticate_admin!

  # GET /assuntos
  # GET /assuntos.xml
  def index
    @assuntos = Assunto.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @assuntos }
    end
  end

  # GET /assuntos/1
  # GET /assuntos/1.xml
  def show
    @assunto = Assunto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @assunto }
    end
  end

  # GET /assuntos/new
  # GET /assuntos/new.xml
  def new
    @assunto = Assunto.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @assunto }
    end
  end

  # GET /assuntos/1/edit
  def edit
    @assunto = Assunto.find(params[:id])
  end

  # POST /assuntos
  # POST /assuntos.xml
  def create
    @assunto = Assunto.new(params[:assunto])

    respond_to do |format|
      if @assunto.save
        format.html { redirect_to(assuntos_url, :notice => 'Assunto was successfully created.') }
        format.xml  { render :xml => @assunto, :status => :created, :location => @assunto }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @assunto.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /assuntos/1
  # PUT /assuntos/1.xml
  def update
    @assunto = Assunto.find(params[:id])

    respond_to do |format|
      if @assunto.update_attributes(params[:assunto])
        format.html { redirect_to(assunto_url, :notice => 'Assunto was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @assunto.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /assuntos/1
  # DELETE /assuntos/1.xml
  def destroy
    @assunto = Assunto.find(params[:id])
    @assunto.destroy

    respond_to do |format|
      format.html { redirect_to(assuntos_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/assuntos_helper.rb
module AssuntosHelper
end

app/views/assuntos/_form.html.erb
# coding: utf-8
<%= form_for(@assunto) do |f| %>
  <% if @assunto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@assunto.errors.count, "error") %> prohibited this assunto from being saved:</h2>

      <ul>
      <% @assunto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :info %><br />
    <%= f.text_field :info %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/assuntos/edit.html.erb
# coding: utf-8
<h1>Alterar assunto</h1>

<%= render 'form' %>

<%= link_to 'Visualizar', @assunto %> |
<%= link_to 'Voltar', assuntos_path %>

app/views/assuntos/index.html.erb
# coding: utf-8
<h1>Manutenção de assuntos</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>User</th>
    <th>Info</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @assuntos.each do |assunto| %>
  <tr>
    <td><%= assunto.nome %></td>
    <td><%= assunto.user %></td>
    <td><%= assunto.info %></td>
    <td><%= link_to 'Visualizar', assunto %></td>
    <td><%= link_to 'Alterar', edit_assunto_path(assunto) %></td>
    <td><%= link_to 'Excluir', assunto, :confirm => 'Confirmar exclusão?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />
<% if Assunto.count == 0%>
<%= link_to 'Incluir Assunto', new_assunto_path %>
<% end %>

app/views/assuntos/new.html.erb
# coding: utf-8
<h1>Incluir assunto</h1>

<%= render 'form' %>

<%= link_to 'Voltar', assuntos_path %>

app/views/assuntos/show.html.erb
# coding: utf-8
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @assunto.nome %>
</p>

<p>
  <b>User:</b>
  <%= @assunto.user %>
</p>

<p>
  <b>Informação:</b>
  <%= @assunto.info %>
</p>


<%= link_to 'Alterar', edit_assunto_path(@assunto) %> |
<%= link_to 'Voltar', assuntos_path %>