config/routes.rb
Teste4::Application.routes.draw do

	match 'm' => 'mobile#index', :as => 'mobile_home'
	match 'm/info' => 'mobile#info', :as => 'mobile_info'
	match 'm/:assunto_id/areas' => 'mobile#lista_area', :as => 'areas_mobile'
	match 'm/:area_id/categorias' => 'mobile#lista_categoria', :as => 'categorias_mobile'
	match 'm/:categoria_id/perfis' => 'mobile#lista_perfil', :as => 'perfis_mobile'
	match 'm/:parm/posts' => 'mobile#twitter', :as => 'twitter_mobile'
	#match 'm/:perfil_id/posts' => 'mobile#twitter', :as => 'twitter_mobile'

	resources :perfis

	resources :categorias

	resources :areas

	resources :assuntos
	
	devise_for :admins,
			:path => '/',
			:path_names => {
				:sign_in  => 'entrar',
				:sign_out => 'sair',
				:sign_up => 'registrar'}

	root :to => "home#index"


	# See how all your routes lay out with "rake routes"
end

app/views/layouts/application.html.erb
# coding: utf-8
<!DOCTYPE html>
<html>
<head>
  <title>Agregador de Informações</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>


<div id="container">
  <div id="main_panel">
    <div class="main_center">
      <div id="main_top_panel">
        <div id="main_top_logo_panel">
          <div class="logo">
            <h1>Agregador de Informações</a></h1>
          </div>
        </div>
        <div id="navigation_panel">
          <div id="topmenu">
			<% if admin_signed_in? %>
			<ul>
			  <li><a href="<%= root_path %>"><span>Home</span></a></li> <!--  class="over" --!>
			  <li><a href="<%= assuntos_path %>"><span>Assuntos</span> </a></li>
			  <li><a href="<%= areas_path %>" ><span>Áreas</span> </a></li>
			  <li><a href="<%= categorias_path %>"><span>Categorias</span> </a></li>
			  <li><a href="<%= perfis_path %>"><span>Perfis</span> </a></li>
			</ul>
			<% end %>
            <div class="clear"></div>
          </div>
        </div>
        <div class="clear"></div>
        <div class="clear"></div>
		<% if admin_signed_in? %>
		<div class="sair"><%= link_to "Sair", destroy_admin_session_path, :method => :delete %></div>
		<% else %>
		<div class="sair"><%= link_to "Entrar", new_admin_session_path %></div>
		<% end %>
      </div>
      <div class="main_controller">
        <div class="main_inner_center">
		
          <div id="main_header_panel">
			<span class="notice"><%= notice %></span>
			<span class="alert"><%= alert %></span>
          </div>
		  
          <div id="main_middle_panel">
            <div class="main_middle_controller">
              <div class="main_middle_details">
			  
				<%= yield %>
			  
                
              </div>
            </div>
          </div>
		  
          <div id="main_header_panel">
          </div>
          <div id="main_header_panel">
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!--
	<div id="main_footer_panel">
	<div class="main_footer_controller">
	<div class="main_center">
	<div class="main_footer_details">

	<h4>&copy; Copyright Luciano R. Costa. All Rights Reserved</h4>

	</div>
	</div>
	</div>
	</div>
-->

</body>
</html>

app/views/layouts/application.mobile.erb
# coding: utf-8
<!DOCTYPE html>
<html>
<head>
  <title><%= @titulo %></title>
  <link rel="stylesheet" href="http://code.jquery.com/mobile/1.0rc2/jquery.mobile-1.0rc2.min.css" />
  <%= javascript_include_tag :defaults %>
  <script src="http://code.jquery.com/mobile/1.0rc2/jquery.mobile-1.0rc2.min.js"></script>
  <%= csrf_meta_tag %>
</head>

<body>
  <div data-role="page">
  
    <%= yield %>
	
  </div>
</body>

</html>